import path from "node:path";

export function resolveOpenCodeConfigDir(
  env: NodeJS.ProcessEnv = process.env,
  home = process.env.HOME ?? "",
): string {
  if (env.OPENCODE_CONFIG_DIR) return env.OPENCODE_CONFIG_DIR;
  if (env.XDG_CONFIG_HOME) return path.join(env.XDG_CONFIG_HOME, "opencode");
  return path.join(home, ".config", "opencode");
}

export function openCodePluginPath(configDir: string): string {
  return path.join(configDir, "plugins", "kiri-friends.js");
}

export function openCodeCommandPath(configDir: string): string {
  return path.join(configDir, "command", "kiri-friends.md");
}

export function openCodePluginSource(port = 7474): string {
  return `// Generated by Kiri Friends.
export const KiriFriendsPlugin = async ({ client }) => {
  const post = async (event, payload) => {
    try {
      await fetch("http://127.0.0.1:${port}/v1/plugin-events", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          version: 1,
          tool: "opencode",
          event,
          createdAt: new Date().toISOString(),
          payload
        })
      });
    } catch {
      // Host CLI must continue when Kiri Friends is unavailable.
    }
  };

  client.hooks.on("tool.execute.before", async (payload) => post("tool.started", payload));
  client.hooks.on("tool.execute.after", async (payload) => post("tool.completed", payload));
  client.hooks.on("session.idle", async (payload) => post("session.completed", payload));
  client.hooks.on("session.error", async (payload) => post("session.failed", payload));
};
`;
}
